# Generated by Django 3.1.5 on 2021-01-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program_Highlights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_Month', models.CharField(max_length=10)),
                ('Class_Size', models.CharField(max_length=10)),
                ('Avg_Work_Experience', models.CharField(max_length=10)),
                ('Avg_Student_Age', models.CharField(max_length=10)),
                ('Women_Students', models.CharField(max_length=10)),
                ('Avg_Salary', models.CharField(max_length=10)),
                ('Scholarship', models.CharField(max_length=10)),
                ('Accreditations', models.CharField(max_length=10)),
            ],
        ),
    ]
