# Generated by Django 3.1.5 on 2021-01-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_program_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='program_highlights',
            name='Rank',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
