# Generated by Django 3.1.5 on 2021-01-17 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_program_highlights_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program_highlights',
            name='Rank',
        ),
        migrations.AddField(
            model_name='program_highlights',
            name='Uniinf',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='firstapp.uniinf'),
            preserve_default=False,
        ),
    ]
